server:
  port: 8080

spring:
  application:
    name: book-mng

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bookmng
    username: user
    password: 1234

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        show_sql: false  # p6spy가 대신 로그를 출력하므로 false로 설정

# query logging
logging:
  level:
    root: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari.HikariDataSource: DEBUG
    com.p6spy.engine.spy.P6SpyDriver: DEBUG

# swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha # 알파벳 순서로 정렬
    operations-sorter: method # 메소드 순서로 정렬
    doc-expansion: none # 카테고리가 접힌상태로 로딩
  #    persist-authorization: true # 브라우저를 새로고침 하더라도 인증정보 유지
  packages-to-scan: com.cdri.bookmng
  title: cdri-book-mng API 문서
  description: cdri-book-mng API 문서
  version: 1.0